[package]
name = "decimal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.20.1"
anchor-spl = "0.20.1"
integer-sqrt = "0.1.5"
uint = "0.9"
