[package]
name = "checked_decimal_macro"
version = "0.1.0"
edition = "2021"
readme = "README.md"
authors = ["Mateusz Zając <matzayonc@gmail.com>"]
repository = "https://github.com/invariant-labs/decimal"

[dependencies]
decimal_core = "0.1.0"
integer-sqrt = "0.1.5"
uint = "0.9"
num-traits = "0.2.14"