name: Test project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

stages:
  - build

jobs:
  rust-latest:
    stage: build
    image: rust:latest
    steps:
      - name: Build and test with Rust latest
        run: |
          cargo build --verbose
          cargo test --verbose

  rust-nightly:
    stage: build
    image: rustlang/rust:nightly
    steps:
      - name: Build and test with Rust nightly
        run: |
          cargo build --verbose
          cargo test --verbose
